# Generated by Django 4.0 on 2021-12-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=30)),
                ('passwd', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('experience', models.EmailField(max_length=30)),
            ],
        ),
    ]
