# Generated by Django 4.0 on 2021-12-29 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='new',
            new_name='new1',
        ),
    ]
